### ISSUE TITLE
[epic] Stride - full architecture implementation

### ISSUE THREAD

**Issue by OriHoch** [hasadna/open-bus#335]
Implement the full architecture of Stride project as detailed in the spec: https://docs.google.com/document/d/1LcGlK0BfJ2C2jE0O0oDBjeidG8KfdNMpGH_bMskdrOc/edit?usp=sharing

**Comment by OriHoch** [comment]
components:
- [x] Siri requester, storage, compressor - https://github.com/hasadna/open-bus-siri-requester
- [x] Siri ETL - https://github.com/hasadna/open-bus-siri-etl
- [x] Airflow server for manual / low frequency jobs - https://github.com/hasadna/open-bus/issues/337
- [x] Data enrichment ETL - https://github.com/hasadna/open-bus/issues/338
- [ ] GTFS ETL - https://github.com/hasadna/open-bus/issues/339
- [ ] REST API - https://github.com/hasadna/open-bus/issues/340
- [ ] Stride DB Archiver / Deleter
